import styles from '../styles/pages/Home.module.css'
import NavBar from '../components/pages/NavBar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>BattleStar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <NavBar />
      <div className={styles.wrapper}>

      </div>
    </>
  )
}
