import styles from '../styles/pages/Settings.module.css';
import NavBar from '../components/pages/NavBar';
import Head from 'next/head';


const settings = () => {

  const scroleBt1 = () => {
    document.getElementById('sc1').removeAttribute('class');
    const sc = document.querySelector('#sc');
    sc.classList.add('Settings_add1__3FMK6');
  }
  const scroleBt2 = () => {
    document.getElementById('sc1').removeAttribute('class');
    const sc = document.querySelector('#sc');
    sc.classList.add('Settings_add2__IBoZm');
  }
  const scroleBt3 = () => {
    document.getElementById('sc1').removeAttribute('class');
    const sc = document.querySelector('#sc');
    sc.classList.add('Settings_add3__xZoR9');
  }
  const scroleBt4 = () => {
    document.getElementById('sc1').removeAttribute('class');
    const sc = document.querySelector('#sc');
    sc.classList.add('Settings_add4__uo_iJ');
  }
  const scroleBt5 = () => {
    document.getElementById('sc1').removeAttribute('class');
    const sc = document.querySelector('#sc');
    sc.classList.add('Settings_add5__7Stwi');
  }
  const scroleBt6 = () => {  
    document.getElementById('sc1').removeAttribute('class');
    const sc = document.querySelector('#sc');
    sc.classList.add('Settings_add6__LYY4L');
  }
    return (
      <div className={styles.wrapper}>        
        <NavBar />
        <Head>
          <title>BattleStar settings</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <div className={styles.contentMain}>
          <div className={styles.topMask}></div>   
          <div className={styles.scrole}>
            <div id='scr' className={styles.scroleButtons}>
              <div id='sc1' onClick={scroleBt1}>
                <a>1</a>
              </div>
              <div id='sc1' onClick={scroleBt2}>
                <a>2</a>
              </div>
              <div id='sc1' onClick={scroleBt3}>
                <a>3</a>
              </div>
              <div id='sc1' onClick={scroleBt4}>
                <a>4</a>
              </div>
              <div id='sc1' onClick={scroleBt5}>
                <a>5</a>
              </div>
              <div id='sc1' onClick={scroleBt6}>
                <a>6</a>
              </div>
            </div>
            <div className={styles.sc}>
              <hr id='sc'/>
            </div>
          </div>
        </div>
      </div>
    );
};

export default settings;